"""initial migration

Revision ID: 06a26c09f7ba
Revises: 
Create Date: 2025-04-30 14:02:47.759152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a26c09f7ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_per_night', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodation_id'), 'accommodation', ['id'], unique=False)
    op.create_index(op.f('ix_accommodation_location'), 'accommodation', ['location'], unique=False)
    op.create_index(op.f('ix_accommodation_name'), 'accommodation', ['name'], unique=False)
    op.create_table('activity',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_category'), 'activity', ['category'], unique=False)
    op.create_index(op.f('ix_activity_id'), 'activity', ['id'], unique=False)
    op.create_index(op.f('ix_activity_location'), 'activity', ['location'], unique=False)
    op.create_index(op.f('ix_activity_name'), 'activity', ['name'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_nights', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_id'), 'itineraries', ['id'], unique=False)
    op.create_index(op.f('ix_itineraries_is_recommended'), 'itineraries', ['is_recommended'], unique=False)
    op.create_index(op.f('ix_itineraries_num_nights'), 'itineraries', ['num_nights'], unique=False)
    op.create_index(op.f('ix_itineraries_region'), 'itineraries', ['region'], unique=False)
    op.create_index(op.f('ix_itineraries_title'), 'itineraries', ['title'], unique=False)
    op.create_table('transfer',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('transport_type', sa.Enum('CAR', 'BUS', 'BOAT', 'FERRY', 'PLANE', name='transporttype'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_destination'), 'transfer', ['destination'], unique=False)
    op.create_index(op.f('ix_transfer_id'), 'transfer', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_source'), 'transfer', ['source'], unique=False)
    op.create_table('itineraryday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraryday_id'), 'itineraryday', ['id'], unique=False)
    op.create_table('day_activities',
    sa.Column('itinerary_day_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itineraryday.id'], ),
    sa.PrimaryKeyConstraint('itinerary_day_id', 'activity_id')
    )
    op.create_table('day_transfers',
    sa.Column('itinerary_day_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itineraryday.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer.id'], ),
    sa.PrimaryKeyConstraint('itinerary_day_id', 'transfer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_transfers')
    op.drop_table('day_activities')
    op.drop_index(op.f('ix_itineraryday_id'), table_name='itineraryday')
    op.drop_table('itineraryday')
    op.drop_index(op.f('ix_transfer_source'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_id'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_destination'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_itineraries_title'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_region'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_num_nights'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_is_recommended'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_id'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_index(op.f('ix_activity_location'), table_name='activity')
    op.drop_index(op.f('ix_activity_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_category'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_accommodation_name'), table_name='accommodation')
    op.drop_index(op.f('ix_accommodation_location'), table_name='accommodation')
    op.drop_index(op.f('ix_accommodation_id'), table_name='accommodation')
    op.drop_table('accommodation')
    # ### end Alembic commands ### 